//! OpenAPI document generation for the space service.
//!
//! Mirrors the pattern established by `im-calls-service::openapi`: the live
//! OpenAPI document is generated by inspecting the router built in
//! `http::build_space_api_routes`, then rendered through
//! `sdkwork_im_openapi::build_openapi_document`. The document is exposed at
//! `/openapi.json` and a human-readable docs page at `/docs`.

use axum::Json;
use axum::response::Html;
use sdkwork_im_api_registry::HttpMethod;
use sdkwork_im_openapi::{
    OpenApiServiceSpec, build_openapi_document, extract_routes_from_function, render_docs_html,
};

pub(crate) async fn openapi_json() -> Json<serde_json::Value> {
    let document = build_space_service_openapi_document().unwrap_or_else(|error| {
        serde_json::json!({
            "openapi": "3.1.0",
            "info": {
                "title": "Sdkwork IM Space Service API",
                "version": env!("CARGO_PKG_VERSION"),
                "description": format!("OpenAPI generation failed: {error}"),
            },
            "paths": {},
        })
    });
    Json(document)
}

pub(crate) async fn docs() -> Html<String> {
    Html(render_docs_html(&space_service_openapi_spec()))
}

fn build_space_service_openapi_document() -> Result<serde_json::Value, String> {
    let routes = extract_routes_from_function(
        include_str!("http.rs"),
        "build_space_api_routes",
        &[],
        &["/openapi.json", "/docs"],
    )?;

    Ok(build_openapi_document(
        &space_service_openapi_spec(),
        &routes,
        space_service_tag,
        space_service_requires_app_context,
        space_service_summary,
    ))
}

fn space_service_openapi_spec() -> OpenApiServiceSpec<'static> {
    OpenApiServiceSpec {
        title: "Sdkwork IM Space Service API",
        version: env!("CARGO_PKG_VERSION"),
        description: "Live OpenAPI contract generated from the space-service router for spaces, members, groups, channels, invitations, and bans.",
        openapi_path: "/openapi.json",
        docs_path: "/docs",
    }
}

fn space_service_tag(path: &str, _method: HttpMethod) -> String {
    if path.starts_with("/im/v3/api/spaces/{spaceId}/members") {
        "space-members".to_owned()
    } else if path.starts_with("/im/v3/api/spaces/{spaceId}/groups") {
        if path.contains("/members") {
            "group-members".to_owned()
        } else {
            "groups".to_owned()
        }
    } else if path.starts_with("/im/v3/api/spaces/{spaceId}/channels") {
        if path.contains("/access_rules") {
            "channel-access-rules".to_owned()
        } else {
            "channels".to_owned()
        }
    } else if path.starts_with("/im/v3/api/spaces/{spaceId}/invites") {
        "invitations".to_owned()
    } else if path.starts_with("/im/v3/api/spaces/{spaceId}/bans") {
        "bans".to_owned()
    } else {
        "spaces".to_owned()
    }
}

fn space_service_requires_app_context(_path: &str, _method: HttpMethod) -> bool {
    // All business routes require an authenticated AppContext.
    true
}

fn space_service_summary(path: &str, method: HttpMethod) -> String {
    match (path, method) {
        ("/im/v3/api/spaces", HttpMethod::Post) => "Create a space".to_owned(),
        ("/im/v3/api/spaces", HttpMethod::Get) => "List accessible spaces".to_owned(),
        ("/im/v3/api/spaces/{spaceId}", HttpMethod::Get) => "Retrieve a space by id".to_owned(),
        ("/im/v3/api/spaces/{spaceId}", HttpMethod::Patch) => "Update space attributes".to_owned(),
        ("/im/v3/api/spaces/{spaceId}", HttpMethod::Delete) => "Delete a space".to_owned(),
        ("/im/v3/api/spaces/{spaceId}/members", HttpMethod::Post) => {
            "Add a member to a space".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/members", HttpMethod::Get) => "List space members".to_owned(),
        ("/im/v3/api/spaces/{spaceId}/members/{userId}", HttpMethod::Get) => {
            "Retrieve a space member".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/members/{userId}", HttpMethod::Patch) => {
            "Update a space member role".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/members/{userId}", HttpMethod::Delete) => {
            "Remove a space member".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups", HttpMethod::Post) => {
            "Create a group within a space".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups", HttpMethod::Get) => "List groups".to_owned(),
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}", HttpMethod::Get) => {
            "Retrieve a group".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}", HttpMethod::Patch) => {
            "Update group attributes".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}", HttpMethod::Delete) => {
            "Delete a group".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}/transfer_owner", HttpMethod::Post) => {
            "Transfer group ownership".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}/members", HttpMethod::Post) => {
            "Add a member to a group".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}/members", HttpMethod::Get) => {
            "List group members".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}/members/{userId}", HttpMethod::Get) => {
            "Retrieve a group member".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}/members/{userId}", HttpMethod::Patch) => {
            "Update a group member".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/groups/{groupId}/members/{userId}", HttpMethod::Delete) => {
            "Remove a group member".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/channels", HttpMethod::Post) => {
            "Create a channel within a space".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/channels", HttpMethod::Get) => "List channels".to_owned(),
        ("/im/v3/api/spaces/{spaceId}/channels/{channelId}", HttpMethod::Get) => {
            "Retrieve a channel".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/channels/{channelId}", HttpMethod::Patch) => {
            "Update channel attributes".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/channels/{channelId}", HttpMethod::Delete) => {
            "Delete a channel".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/channels/{channelId}/access_rules", HttpMethod::Post) => {
            "Create a channel access rule".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/channels/{channelId}/access_rules", HttpMethod::Get) => {
            "List channel access rules".to_owned()
        }
        (
            "/im/v3/api/spaces/{spaceId}/channels/{channelId}/access_rules/{ruleId}",
            HttpMethod::Delete,
        ) => "Delete a channel access rule".to_owned(),
        ("/im/v3/api/spaces/{spaceId}/invites", HttpMethod::Post) => {
            "Create a space invitation".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/invites", HttpMethod::Get) => {
            "List space invitations".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/invites/{inviteCode}", HttpMethod::Get) => {
            "Retrieve a space invitation".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/invites/{inviteCode}", HttpMethod::Delete) => {
            "Revoke a space invitation".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/invites/{inviteCode}/accept", HttpMethod::Post) => {
            "Accept a space invitation".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/bans", HttpMethod::Post) => {
            "Ban a user from a space".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/bans", HttpMethod::Get) => "List space bans".to_owned(),
        ("/im/v3/api/spaces/{spaceId}/bans/{userId}", HttpMethod::Get) => {
            "Retrieve a space ban record".to_owned()
        }
        ("/im/v3/api/spaces/{spaceId}/bans/{userId}", HttpMethod::Delete) => {
            "Revoke a space ban".to_owned()
        }
        _ => format!("{method:?} {path}"),
    }
}
